# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PapCult
email: your-email@domain.com
description: "A comedy show which looks at the popular, the cool and the fashionable, tearing apart the very fabric of modern life. Every episode covers something from the worlds of comedy, music, movies, gaming, technology, news, or something else entirely. Hosted by the writers, comedians and Scottish cultural icons Cameron Nicolson and Fraser McGovern, who are qualifed in everything about nothing. Join our cult."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.papcult.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


# Podcast settings
podcast_url: http://www.papcult.com/podcast
podcast_album_art: https://s3-eu-west-1.amazonaws.com/images.papcult.com/iTunes-Papcult-Album-Art.jpg
podcast_title: PapCult
podcast_owner: "Cameron Nicolson, Fraser McGovern"
podcast_email: email@example.com
podcast_category: Comedy
podcast_subcategory_one: "Society &amp; Culture"
podcast_subcategory_two: "Arts"
podcast_explicit: "no"
podcast_author: PapCult
podcast_description: "A comedy show which looks at the popular, the cool and the fashionable, tearing apart the very fabric of modern life. Every episode covers something from the worlds of comedy, music, movies, gaming, technology, news, or something else entirely. Hosted by the writers, comedians and Scottish cultural icons Cameron Nicolson and Fraser McGovern, who are qualifed in everything about nothing. Join our cult."
podcast_summary: "A comedic a look at the popular, the cool and the fashionable with Scottish cultural icons Cameron Nicolson and Fraser McGovern."
podcast_subtitle: "Culture... papped."